#!/usr/bin/env python3
"""Generate the KiCad footprint for TI package DGS0028A (28-pin VSSOP).

Every dimension below is read directly from the primary source -- REFERENCES.md
[43], TI *MSPM0G3507-Q1, MSPM0G3506-Q1, MSPM0G3505-Q1* datasheet SLASF88C
(Oct 2023, rev. Sep 2025), local copy `docs/datasheets/mspm0g3507-q1.pdf`,
Section 12 "Mechanical, Packaging, and Orderable Information", drawing
4226365/A (10/2020), sheets "PACKAGE OUTLINE" and "EXAMPLE BOARD LAYOUT" for
DGS0028A.  Nothing here is inferred from a generic IPC family rule or from a
lookalike footprint: KiCad 9.0.2's standard libraries ship no VSSOP-28
footprint at all (checked: Package_SO.pretty and every other .pretty), which
is why this is generated rather than referenced.

Per AGENTS.md SS1.3, each constant carries the sheet it came from.  Change a
number here and regenerate; never hand-edit the .kicad_mod.

Usage:
    python3 gen_dgs0028a_footprint.py -o ../footprints/Open_Secure_ESC.pretty
"""

import argparse
import sys
from pathlib import Path

from kiutils.footprint import Attributes, Footprint, Pad
from kiutils.items.common import Position
from kiutils.items.fpitems import FpLine, FpText

# ---------------------------------------------------------------------------
# Dimensions, all from drawing 4226365/A (see module docstring).
# ---------------------------------------------------------------------------
# "EXAMPLE BOARD LAYOUT" sheet -- the manufacturer's recommended land pattern:
PAD_LEN = 1.45  # "28X (1.45)" -- pad length, along the lead axis (X here)
PAD_WID = 0.30  # "28X (0.3)"  -- pad width, along the pitch axis (Y here)
PITCH = 0.50  # "26X (0.5)"  -- 13 spaces per side x 2 sides = 26
ROW_SPAN = 4.40  # "(4.4)"      -- centreline-to-centreline of the two rows

# "PACKAGE OUTLINE" sheet -- the physical body, used for F.Fab/silk/courtyard:
BODY_LEN = 7.10  # D  = 7.2 / 7.0 -> 7.1 nominal (note 3: excludes mold flash)
BODY_WID = 3.00  # E1 = 3.1 / 2.9 -> 3.0 nominal
LEAD_SPAN = 5.10  # E  = 5.1 / 4.7 -> use the MAX for courtyard safety

PINS_PER_SIDE = 14  # 28 pins, "1" and "14" left, "15" and "28" right

# KiCad house style (not datasheet values -- drawing/DRC conventions only):
CRTYD_CLEARANCE = 0.25
SILK_CLEARANCE = 0.11
LINE_FAB = 0.10
LINE_SILK = 0.12
LINE_CRTYD = 0.05

NAME = "Texas_DGS0028A_VSSOP-28_3x7.1mm_P0.5mm"


def _line(start, end, layer, width):
    return FpLine(
        start=Position(round(start[0], 4), round(start[1], 4)),
        end=Position(round(end[0], 4), round(end[1], 4)),
        layer=layer,
        width=width,
    )


def _rect(half_x, half_y, layer, width):
    """Four lines forming a rectangle centred on the origin."""
    c = [(-half_x, -half_y), (half_x, -half_y), (half_x, half_y), (-half_x, half_y)]
    return [_line(c[i], c[(i + 1) % 4], layer, width) for i in range(4)]


def build() -> Footprint:
    fp = Footprint(
        libraryNickname="Open_Secure_ESC",
        entryName=NAME,
        version="20211014",
        generator="open_secure_esc_fpgen",
        layer="F.Cu",
        description=(
            "Texas Instruments DGS0028A, 28-pin VSSOP, 0.5 mm pitch, "
            "body 3.0 x 7.1 mm, lead span 5.1 mm max, 1.1 mm max height. "
            "Land pattern per TI drawing 4226365/A 'EXAMPLE BOARD LAYOUT'. "
            "Generated by symbols/tools/gen_dgs0028a_footprint.py from "
            "REFERENCES.md [43] Section 12 -- do not hand-edit."
        ),
        tags="VSSOP DGS0028A DGS28 SSOP TI SMD",
        attributes=Attributes(type="smd"),
    )

    # --- Reference/value text, clear of the body on F.SilkS / F.Fab ---
    text_y = BODY_LEN / 2 + 1.0
    fp.graphicItems.append(
        FpText(
            type="reference",
            text="REF**",
            position=Position(0, -text_y, 0),
            layer="F.SilkS",
        )
    )
    fp.graphicItems.append(
        FpText(type="value", text=NAME, position=Position(0, text_y, 0), layer="F.Fab")
    )

    # --- Pads: 1..14 down the left row, 15..28 up the right row ---
    # (matches the datasheet's own "LAND PATTERN EXAMPLE" numbering, where
    #  pin 1 and pin 28 are at the same end of the package.)
    y0 = -PITCH * (PINS_PER_SIDE - 1) / 2
    x = ROW_SPAN / 2
    for i in range(PINS_PER_SIDE):
        y = y0 + i * PITCH
        for number, px in ((i + 1, -x), (2 * PINS_PER_SIDE - i, x)):
            fp.pads.append(
                Pad(
                    number=str(number),
                    type="smd",
                    shape="roundrect",
                    roundrectRatio=0.25,
                    position=Position(round(px, 4), round(y, 4)),
                    size=Position(PAD_LEN, PAD_WID),
                    layers=["F.Cu", "F.Paste", "F.Mask"],
                )
            )

    # --- F.Fab: true body outline, with a chamfer marking pin 1 ---
    hx, hy = BODY_WID / 2, BODY_LEN / 2
    ch = 0.6
    fab = [
        ((-hx + ch, -hy), (hx, -hy)),
        ((hx, -hy), (hx, hy)),
        ((hx, hy), (-hx, hy)),
        ((-hx, hy), (-hx, -hy + ch)),
        ((-hx, -hy + ch), (-hx + ch, -hy)),
    ]
    for s, e in fab:
        fp.graphicItems.append(_line(s, e, "F.Fab", LINE_FAB))

    # --- F.SilkS: body edges only where they clear the pads, + pin-1 dot ---
    pad_edge_y = y0 - PAD_WID / 2 - SILK_CLEARANCE
    for sx in (-1, 1):
        fp.graphicItems.append(
            _line((sx * hx, -hy), (sx * hx, pad_edge_y), "F.SilkS", LINE_SILK)
        )
        fp.graphicItems.append(
            _line((sx * hx, -pad_edge_y), (sx * hx, hy), "F.SilkS", LINE_SILK)
        )
    fp.graphicItems.append(_line((-hx, -hy), (hx, -hy), "F.SilkS", LINE_SILK))
    fp.graphicItems.append(_line((-hx, hy), (hx, hy), "F.SilkS", LINE_SILK))
    # Pin-1 marker, outboard of pad 1 so it survives assembly silk trimming.
    p1x = ROW_SPAN / 2 + PAD_LEN / 2 + SILK_CLEARANCE + 0.15
    fp.graphicItems.append(
        _line((-p1x, y0 - 0.2), (-p1x, y0 + 0.2), "F.SilkS", LINE_SILK)
    )

    # --- F.CrtYd: encloses whichever is wider, the pads or the lead span ---
    crtyd_x = max(LEAD_SPAN / 2, ROW_SPAN / 2 + PAD_LEN / 2) + CRTYD_CLEARANCE
    crtyd_y = max(BODY_LEN / 2, -y0 + PAD_WID / 2) + CRTYD_CLEARANCE
    fp.graphicItems.extend(_rect(crtyd_x, crtyd_y, "F.CrtYd", LINE_CRTYD))

    return fp


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-o", "--outdir", default=".", help="Output .pretty directory")
    args = ap.parse_args(argv)

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    out = outdir / f"{NAME}.kicad_mod"
    out.write_text(build().to_sexpr())
    print(f"wrote {out} (28 pads)")


if __name__ == "__main__":
    sys.exit(main())
